name: Delete Old Workflows 删除过时工作流程

permissions: write-all

on:
  workflow_dispatch:

  #schedule:
   # - cron: '0 5 * * 2'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 2
